Eunju/11
handong-app/project-t pull request #9
Opened 2024-06-29 07:33 UTC by ejPark43

2024-06-29 10:56 UTC, junglesub reviewed
고생하셨습니다!

확인해 보니깐 public 폴더에 있는 svg 나 atom.jsx 처럼 삭제된 파일이 있던데 혹시 이 부분은 의도하신게 맞으신가요?

2024-06-29 11:44 UTC, ejPark43 commented
파일을 삭제한건 아니고 제가 수정한 부분만 커밋하려고 add할때 제외했던것 같습니당

2024-06-29 11:51 UTC, junglesub commented
> 파일을 삭제한건 아니고 제가 수정한 부분만 커밋하려고 add할때 제외했던것 같습니당

넵! 지금 상태로 머지되면 메인에 있는 파일이 삭제될 수가 있어서 수정을 해봐야할 것 같습니다.

혼자 작업하신 브랜치면 커밋을 수정하신 후에 force push 해주셔도 좋고, 아니면 삭제하는 커밋을 롤백하고 다시 커밋해주셔도 좋을 것 같습니다.

https://github.com/handong-app/project-t/pull/9/commits/b4631092db8ca617d88a0fd3bdead18d56a6827e

위 커밋에서 삭제된 것 같아요!

2024-06-29 16:19 UTC, ejPark43 commented
해당 커밋 부분에서 revert로 해결하려고 했는데 중간에  과정이 꼬이는 바람에, 삭제된 파일들을 추가하고 add 한뒤 커밋하는 방향으로 했습니답 이렇게 하면 문제가 없을까요?

2024-06-30 00:48 UTC, junglesub requested changes
지워진 파일 잘 추가된 것을 확인했습니다!

react-datepicker, @mui/icons-material 같은 새로운 dependencies 를 사용하신 것 같은데 package.json 에는 빠져있습니다. 혹시 잘 추가가 되었는지, 커밋 되었는지 확인 부탁드려도 괜찮을까요?

2024-06-30 03:43 UTC, ejPark43 commented
새로운 dependency를 쓰고 업데이트된 package.json 내용을 커밋 하지 않은 상태에서 pull을 받아서 메인 내용이 덮어씌워진 것 같습니다! node_modules에서 남아있었는지 테스트할때 해당 기능들 사용이 가능해서 인지를 못하고 있었네요. 다시 설치하고 커밋하겠습니다

2024-06-30 08:08 UTC, junglesub approved these changes
감사합니다!

@mui/icons-material 을 사용하기 위해서는 base package 인 @mui/material 을 설치해야한다고 합니다. 또한 필수 패키지인 @emotion/react 와 styled 도 설치해주었습니다.

설치하고 실행하니 정상 작동 하는 것을 확인했습니다. 고생하셨습니다~

2024-06-30 08:57 UTC, merged